### PR TITLE
Allow request kwargs

### PR DESCRIPTION
**Pull request by zulrang**
Allow load_x509_cert and KEYS.load_from_url to accept kwargs to pass through to request

### CODE REVIEW

**Comment by zulrang** [comment]
Tests would not pass before the change.

**Comment by zulrang** [comment]
Fixes https://github.com/IdentityPython/pyjwkest/issues/80

**Comment by rohe** [comment]
I have nothing against the PR as such but I don't like that so many tests doesn't pass.
When did this happen ?

**Comment by zulrang** [comment]
If I just git clone master and run tox, I get the same failures on an EC2 instance.

**Comment by rohe** [comment]
OK, I'll fix the tests but probably not until tomorrow.

**Comment by rohe** [comment]
I've push some changes. Can you verify that the tests works now. They do for me.

**Comment by zulrang** [comment]
I'm not seeing any changes.  Last commit was from Oct. https://github.com/IdentityPython/pyjwkest/commit/0c75bc631d1fae5e190d857fc616c4cba5be6b31

**Pull request merged**
